### ISSUE TITLE
Data gathering

### ISSUE THREAD

**Issue by nilodna** [oceanhackweek/OHW22_SA_ocean_db#6]
In this step of our project, we have to code a collection of functions to download the PNBOIA data, using their API and saving it as a .csv locally. 

@douglasnehme will code these functions, to download operationally the last 5-days of data available for 4 active buoys, appending the new observations with the old observations.

**Comment by douglasnehme** [comment]
I implement all the Danilo's and Tobias' suggestions. Besides this I improve the script performance reducing the number of unnecessary connections to the API and using the  pd.read_csv function more efficiently.
